=== Etienne0812/XSLTpractice/spain_output.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.etienne.com"
           xmlns="https://www.etienne.com"
           elementFormDefault="qualified">
    
    <xs:element name="records" type="records"/>

    <xs:complexType name="records">
        <xs:sequence>
            <xs:element ref="record" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="record">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="date" type="date"/>
                <xs:element name="cases" type="xs:integer"/>
                <xs:element name="deaths" type="xs:integer"/>
                <xs:element name="population" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="date">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}/\d{2}/\d{4}"/>
        </xs:restriction>
    </xs:simpleType>
   

</xs:schema>

=== Etienne0812/XSLTpractice/spain_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<records xsi:schemaLocation="https://www.etienne.com spain_output.xsd" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xmlns="https://www.etienne.com">
    <record>
        <date>03/04/2020</date>
        <cases>8102</cases>
        <deaths>950</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>02/04/2020</date>
        <cases>7719</cases>
        <deaths>864</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>01/04/2020</date>
        <cases>9222</cases>
        <deaths>849</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>31/03/2020</date>
        <cases>6398</cases>
        <deaths>812</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>30/03/2020</date>
        <cases>6549</cases>
        <deaths>838</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>29/03/2020</date>
        <cases>8189</cases>
        <deaths>832</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>28/03/2020</date>
        <cases>7871</cases>
        <deaths>769</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>27/03/2020</date>
        <cases>8578</cases>
        <deaths>655</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>26/03/2020</date>
        <cases>7937</cases>
        <deaths>738</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>25/03/2020</date>
        <cases>6584</cases>
        <deaths>514</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>24/03/2020</date>
        <cases>4517</cases>
        <deaths>462</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>23/03/2020</date>
        <cases>3646</cases>
        <deaths>394</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>22/03/2020</date>
        <cases>4946</cases>
        <deaths>324</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>21/03/2020</date>
        <cases>2833</cases>
        <deaths>235</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>20/03/2020</date>
        <cases>3431</cases>
        <deaths>169</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>19/03/2020</date>
        <cases>2538</cases>
        <deaths>107</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>18/03/2020</date>
        <cases>1987</cases>
        <deaths>182</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>17/03/2020</date>
        <cases>1438</cases>
        <deaths>21</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>16/03/2020</date>
        <cases>2000</cases>
        <deaths>152</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>15/03/2020</date>
        <cases>1522</cases>
        <deaths>15</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>14/03/2020</date>
        <cases>1227</cases>
        <deaths>37</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>13/03/2020</date>
        <cases>864</cases>
        <deaths>37</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>12/03/2020</date>
        <cases>501</cases>
        <deaths>12</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>11/03/2020</date>
        <cases>435</cases>
        <deaths>7</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>10/03/2020</date>
        <cases>615</cases>
        <deaths>23</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>09/03/2020</date>
        <cases>159</cases>
        <deaths>0</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>08/03/2020</date>
        <cases>56</cases>
        <deaths>0</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>07/03/2020</date>
        <cases>113</cases>
        <deaths>2</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>06/03/2020</date>
        <cases>61</cases>
        <deaths>2</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>05/03/2020</date>
        <cases>49</cases>
        <deaths>1</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>04/03/2020</date>
        <cases>37</cases>
        <deaths>0</deaths>
        <population>46723749</population>
    </record>
    <record>
        <date>03/03/2020</date>
        <cases>31</cases>
        <deaths>0</deaths>
        <population>46723749</population>
    </record>
</records>
